// top_emif_0_altera_mm_interconnect_191_3yb4cia.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module top_emif_0_altera_mm_interconnect_191_3yb4cia (
		input  wire [31:0] colmaster_master_address,                         //                           colmaster_master.address
		output wire        colmaster_master_waitrequest,                     //                                           .waitrequest
		input  wire [3:0]  colmaster_master_byteenable,                      //                                           .byteenable
		input  wire        colmaster_master_read,                            //                                           .read
		output wire [31:0] colmaster_master_readdata,                        //                                           .readdata
		output wire        colmaster_master_readdatavalid,                   //                                           .readdatavalid
		input  wire        colmaster_master_write,                           //                                           .write
		input  wire [31:0] colmaster_master_writedata,                       //                                           .writedata
		output wire [29:0] avl_bridge_out_s0_address,                        //                          avl_bridge_out_s0.address
		output wire        avl_bridge_out_s0_write,                          //                                           .write
		output wire        avl_bridge_out_s0_read,                           //                                           .read
		input  wire [31:0] avl_bridge_out_s0_readdata,                       //                                           .readdata
		output wire [31:0] avl_bridge_out_s0_writedata,                      //                                           .writedata
		output wire [0:0]  avl_bridge_out_s0_burstcount,                     //                                           .burstcount
		output wire [3:0]  avl_bridge_out_s0_byteenable,                     //                                           .byteenable
		input  wire        avl_bridge_out_s0_readdatavalid,                  //                                           .readdatavalid
		input  wire        avl_bridge_out_s0_waitrequest,                    //                                           .waitrequest
		output wire        avl_bridge_out_s0_debugaccess,                    //                                           .debugaccess
		input  wire        avl_bridge_out_reset_reset_bridge_in_reset_reset, // avl_bridge_out_reset_reset_bridge_in_reset.reset
		input  wire        clk_bridge_out_clk_1_clk                          //                       clk_bridge_out_clk_1.clk
	);

	wire         colmaster_master_translator_avalon_universal_master_0_waitrequest;   // avl_bridge_out_s0_translator:uav_waitrequest -> colmaster_master_translator:uav_waitrequest
	wire  [31:0] colmaster_master_translator_avalon_universal_master_0_readdata;      // avl_bridge_out_s0_translator:uav_readdata -> colmaster_master_translator:uav_readdata
	wire         colmaster_master_translator_avalon_universal_master_0_debugaccess;   // colmaster_master_translator:uav_debugaccess -> avl_bridge_out_s0_translator:uav_debugaccess
	wire  [31:0] colmaster_master_translator_avalon_universal_master_0_address;       // colmaster_master_translator:uav_address -> avl_bridge_out_s0_translator:uav_address
	wire         colmaster_master_translator_avalon_universal_master_0_read;          // colmaster_master_translator:uav_read -> avl_bridge_out_s0_translator:uav_read
	wire   [3:0] colmaster_master_translator_avalon_universal_master_0_byteenable;    // colmaster_master_translator:uav_byteenable -> avl_bridge_out_s0_translator:uav_byteenable
	wire         colmaster_master_translator_avalon_universal_master_0_readdatavalid; // avl_bridge_out_s0_translator:uav_readdatavalid -> colmaster_master_translator:uav_readdatavalid
	wire         colmaster_master_translator_avalon_universal_master_0_lock;          // colmaster_master_translator:uav_lock -> avl_bridge_out_s0_translator:uav_lock
	wire         colmaster_master_translator_avalon_universal_master_0_write;         // colmaster_master_translator:uav_write -> avl_bridge_out_s0_translator:uav_write
	wire  [31:0] colmaster_master_translator_avalon_universal_master_0_writedata;     // colmaster_master_translator:uav_writedata -> avl_bridge_out_s0_translator:uav_writedata
	wire   [2:0] colmaster_master_translator_avalon_universal_master_0_burstcount;    // colmaster_master_translator:uav_burstcount -> avl_bridge_out_s0_translator:uav_burstcount

	top_emif_0_altera_merlin_master_translator_191_g7h47bq #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (0),
		.WAITREQUEST_ALLOWANCE       (0)
	) colmaster_master_translator (
		.clk                    (clk_bridge_out_clk_1_clk),                                            //   input,   width = 1,                       clk.clk
		.reset                  (avl_bridge_out_reset_reset_bridge_in_reset_reset),                    //   input,   width = 1,                     reset.reset
		.uav_address            (colmaster_master_translator_avalon_universal_master_0_address),       //  output,  width = 32, avalon_universal_master_0.address
		.uav_burstcount         (colmaster_master_translator_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read               (colmaster_master_translator_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write              (colmaster_master_translator_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest        (colmaster_master_translator_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (colmaster_master_translator_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (colmaster_master_translator_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata           (colmaster_master_translator_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata          (colmaster_master_translator_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock               (colmaster_master_translator_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess        (colmaster_master_translator_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.av_address             (colmaster_master_address),                                            //   input,  width = 32,      avalon_anti_master_0.address
		.av_waitrequest         (colmaster_master_waitrequest),                                        //  output,   width = 1,                          .waitrequest
		.av_byteenable          (colmaster_master_byteenable),                                         //   input,   width = 4,                          .byteenable
		.av_read                (colmaster_master_read),                                               //   input,   width = 1,                          .read
		.av_readdata            (colmaster_master_readdata),                                           //  output,  width = 32,                          .readdata
		.av_readdatavalid       (colmaster_master_readdatavalid),                                      //  output,   width = 1,                          .readdatavalid
		.av_write               (colmaster_master_write),                                              //   input,   width = 1,                          .write
		.av_writedata           (colmaster_master_writedata),                                          //   input,  width = 32,                          .writedata
		.av_burstcount          (1'b1),                                                                // (terminated),                                        
		.av_beginbursttransfer  (1'b0),                                                                // (terminated),                                        
		.av_begintransfer       (1'b0),                                                                // (terminated),                                        
		.av_chipselect          (1'b0),                                                                // (terminated),                                        
		.av_lock                (1'b0),                                                                // (terminated),                                        
		.av_debugaccess         (1'b0),                                                                // (terminated),                                        
		.uav_clken              (),                                                                    // (terminated),                                        
		.av_clken               (1'b1),                                                                // (terminated),                                        
		.uav_response           (2'b00),                                                               // (terminated),                                        
		.av_response            (),                                                                    // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                                // (terminated),                                        
		.av_writeresponsevalid  ()                                                                     // (terminated),                                        
	);

	top_emif_0_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (30),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (0)
	) avl_bridge_out_s0_translator (
		.clk                    (clk_bridge_out_clk_1_clk),                                            //   input,   width = 1,                      clk.clk
		.reset                  (avl_bridge_out_reset_reset_bridge_in_reset_reset),                    //   input,   width = 1,                    reset.reset
		.uav_address            (colmaster_master_translator_avalon_universal_master_0_address),       //   input,  width = 32, avalon_universal_slave_0.address
		.uav_burstcount         (colmaster_master_translator_avalon_universal_master_0_burstcount),    //   input,   width = 3,                         .burstcount
		.uav_read               (colmaster_master_translator_avalon_universal_master_0_read),          //   input,   width = 1,                         .read
		.uav_write              (colmaster_master_translator_avalon_universal_master_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest        (colmaster_master_translator_avalon_universal_master_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (colmaster_master_translator_avalon_universal_master_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (colmaster_master_translator_avalon_universal_master_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata           (colmaster_master_translator_avalon_universal_master_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata          (colmaster_master_translator_avalon_universal_master_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock               (colmaster_master_translator_avalon_universal_master_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess        (colmaster_master_translator_avalon_universal_master_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.av_address             (avl_bridge_out_s0_address),                                           //  output,  width = 30,      avalon_anti_slave_0.address
		.av_write               (avl_bridge_out_s0_write),                                             //  output,   width = 1,                         .write
		.av_read                (avl_bridge_out_s0_read),                                              //  output,   width = 1,                         .read
		.av_readdata            (avl_bridge_out_s0_readdata),                                          //   input,  width = 32,                         .readdata
		.av_writedata           (avl_bridge_out_s0_writedata),                                         //  output,  width = 32,                         .writedata
		.av_burstcount          (avl_bridge_out_s0_burstcount),                                        //  output,   width = 1,                         .burstcount
		.av_byteenable          (avl_bridge_out_s0_byteenable),                                        //  output,   width = 4,                         .byteenable
		.av_readdatavalid       (avl_bridge_out_s0_readdatavalid),                                     //   input,   width = 1,                         .readdatavalid
		.av_waitrequest         (avl_bridge_out_s0_waitrequest),                                       //   input,   width = 1,                         .waitrequest
		.av_debugaccess         (avl_bridge_out_s0_debugaccess),                                       //  output,   width = 1,                         .debugaccess
		.av_begintransfer       (),                                                                    // (terminated),                                       
		.av_beginbursttransfer  (),                                                                    // (terminated),                                       
		.av_writebyteenable     (),                                                                    // (terminated),                                       
		.av_lock                (),                                                                    // (terminated),                                       
		.av_chipselect          (),                                                                    // (terminated),                                       
		.av_clken               (),                                                                    // (terminated),                                       
		.uav_clken              (1'b0),                                                                // (terminated),                                       
		.av_outputenable        (),                                                                    // (terminated),                                       
		.uav_response           (),                                                                    // (terminated),                                       
		.av_response            (2'b00),                                                               // (terminated),                                       
		.uav_writeresponsevalid (),                                                                    // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                                                 // (terminated),                                       
	);

endmodule
